image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - lint

install:
  stage: install
  script:
    - npm install
test:
  stage: test
  script:
    - npm test

lint:
  stage: lint
  script:
    - npm run lint
